name: Maestro CI

on:
  workflow_dispatch:  # 🚀 Manual trigger only  

#on:
 # push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java (required for Maestro)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0' # or your current version

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Set up Android Emulator & Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: pixel_4
        script: |
          mkdir -p artifacts/Reports
          adb devices

          # Build & install app
          flutter build apk --debug
          adb install build/app/outputs/flutter-apk/app-debug.apk

          # Run Maestro tests
          maestro --version
          maestro test flows/ --format junit --output artifacts/Reports/test-results.xml

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: maestro-test-results
        path: artifacts/Reports/test-results.xml
